import {describe,it,expect} from 'vitest';
import {blankScenario,validateScenario,type ScenarioPreset} from './ScenarioPreset';
import {instantiateScenario,emptyScenarioWorld} from './instantiateScenario';
import {ScenarioDocument} from '../dev/ScenarioDocument';
import {WorldSession,simulationPort} from '../sessions/WorldSession';
import {observeFaction} from '../operations/EnemyCommander';
import {TerrainSystem} from '../terrain/TerrainSystem';

function fixture():ScenarioPreset{
 const p=blankScenario(),terrain=new TerrainSystem(emptyScenarioWorld());let place={x:0,z:0};
 for(let x=-1400;x<-900;x+=25){const z=-1500;if([-7,0,7].every(dx=>!terrain.obstacleAt(x+dx,z,.3)&&terrain.groundTypeAt(x+dx,z)!=='river')){place={x,z};break;}}
 p.entities=[{id:'alpha',name:'Alpha',type:'formation',side:'player',kind:'rifle',count:2,intent:'attack',...place,ammo:20,food:2,water:3},{id:'bravo',name:'Bravo',type:'formation',side:'enemy',kind:'rifle',count:2,intent:'hold',...place,ammo:20,food:2,water:3},{id:'flag',name:'Flag',type:'objective',owner:'neutral',x:place.x+50,z:place.z,radius:20}];return p;
}
describe('authored scenario contract and source isolation',()=>{
 it('constructs identical independent production worlds and explicit finite manifests',()=>{const p=fixture(),source=JSON.stringify(p),a=instantiateScenario(p),b=instantiateScenario(p);expect(a).toEqual(b);expect(a).not.toBe(b);expect(a.living!.trucks).toEqual([]);expect(a.living!.rearStock.ammo).toBe(0);expect(a.living!.ledger.initial.ammo).toBe(80);expect(a.living!.ledger.initial.water).toBe(12);a.soldiers[0].health=0;a.soldiers[0].carried!.ammo=0;expect(JSON.stringify(p)).toBe(source);expect(b.soldiers[0].health).toBe(100);});
 it('rejects incompatible versions, unknown runtime state, malformed stocks and broken references',()=>{const p=fixture();for(const bad of [{...p,version:9},{...p,worldSize:3000},{...p,id:'catalogue'},{...p,id:'con'},{...p,soldiers:[]},{...p,camera:{...p.camera,x:NaN}},{...p,entities:[{...p.entities[0],id:'broken"id'}]},{...p,entities:[{...p.entities[0],targetId:'missing'}]},{...p,entities:[{...p.entities[0],count:1.5}]},{...p,entities:[{...p.entities[0],suppression:80}]}])expect(()=>validateScenario(bad)).toThrow('Scenario:');});
 it('supports reversible edits, dirty save failure, identity duplication and clean reopen',()=>{const doc=new ScenarioDocument();doc.load(fixture());const original=JSON.stringify(doc.preset);doc.change(p=>{p.entities[0].name='Changed';});expect(doc.dirty).toBe(true);doc.undo();expect(JSON.stringify(doc.preset)).toBe(original);expect(doc.dirty).toBe(false);doc.redo();expect(doc.dirty).toBe(true);const saved=JSON.stringify(doc.preset);doc.markSaved(saved);doc.duplicate('different-file');expect(doc.preset.id).toBe('different-file');expect(doc.dirty).toBe(true);doc.load(JSON.parse(saved));expect(doc.dirty).toBe(false);});
 it('cannot start opposing factions owning one connected trench',()=>{const p=blankScenario();p.entities=[{id:'a',name:'A',type:'trench',side:'player',points:[{x:-1400,z:-1500},{x:-1370,z:-1500}],completed:true,width:4.2,depth:1.75},{id:'b',name:'B',type:'trench',side:'enemy',points:[{x:-1370,z:-1500},{x:-1340,z:-1500}],completed:true,width:4.2,depth:1.75}];expect(()=>instantiateScenario(p)).toThrow();});
});
describe('world session ownership',()=>{
 it('rejects campaign saves from editor and attract; disposal is idempotent and disables stepping',()=>{const before=WorldSession.ownership.active;for(const kind of ['attract','editor-test'] as const){const s=new WorldSession(kind,instantiateScenario(blankScenario()),false);expect(()=>s.save(()=>true)).toThrow('Only an active player');s.dispose();s.dispose();const time=s.state.elapsed;s.step();expect(s.state.elapsed).toBe(time);expect(s.lifetime.signal.aborted).toBe(true);}expect(WorldSession.ownership.active).toBe(before);const player=new WorldSession('player',instantiateScenario(blankScenario()),false);expect(player.save(s=>s.seed)).toBe(1944);player.dispose();});
 it('keeps a stable render/UI port while completely replacing simulation ownership',()=>{let s=new WorldSession('player',instantiateScenario(blankScenario()),false);const port=simulationPort(()=>s.simulation),terrain=port.terrain,network=port.garrisons.network,old=s.simulation;const next=blankScenario();next.seed=42;s.dispose();s=new WorldSession('attract',instantiateScenario(next),false);expect(port.state.seed).toBe(42);expect(terrain.seed).toBe(42);expect(port.garrisons.network).toBe(network);expect(s.simulation).not.toBe(old);s.dispose();});
 it('survives 30 transitions and 10 resets without retained active owners or affecting fresh random results',()=>{const baseline=JSON.stringify(instantiateScenario(fixture())),before=WorldSession.ownership.active;for(let n=0;n<40;n++){const s=new WorldSession(n<30?'player':'attract',instantiateScenario(fixture()),false);s.step();s.dispose();}expect(WorldSession.ownership.active).toBe(before);expect(JSON.stringify(instantiateScenario(fixture()))).toBe(baseline);});
 it('exposes only the correct faction reports to the shared commander, even for spectator worlds',()=>{const s=instantiateScenario(fixture()),op=s.operation!;op.contacts={player:[],enemy:[]};const before=observeFaction(s,'player');s.soldiers.filter(p=>s.squads.find(q=>q.id===p.squadId)?.faction==='enemy').forEach(p=>{p.x+=400;p.health=5;});expect(observeFaction(s,'player')).toEqual(before);expect(before.squads.every(q=>s.squads.find(v=>v.id===q.id)?.faction==='player')).toBe(true);expect(observeFaction(s,'enemy').squads.every(q=>s.squads.find(v=>v.id===q.id)?.faction==='enemy')).toBe(true);});
});
