import './style.css';
import {ScenarioDocument} from './ScenarioDocument';
import {FolderStore} from './FolderStore';
import {EditorView} from './EditorView';
import {blankScenario,INTENTIONS,type ScenarioEntity,type ScenarioPreset} from '../scenarios/ScenarioPreset';
import {instantiateScenario} from '../scenarios/instantiateScenario';
import {inventory,RESOURCES} from '../garrison/types';
import {distance,distanceToSegment,polylineLength,type Vec2} from '../core/types';
import {productionTrenchPath} from '../construction/TrenchSystem';
import {WorldSession} from '../sessions/WorldSession';

const doc=new ScenarioDocument(),store=new FolderStore(),root=document.querySelector<HTMLElement>('#dev-ui')!,canvas=document.querySelector<HTMLCanvasElement>('#battlefield')!;
let message='Author initial conditions. Terrain, roads, forests and buildings are generated and read-only.',selected:string|undefined,tool='select',side:'player'|'enemy'='player',serial=1,projectFolder:string|undefined,busy=false;
const view=new EditorView(canvas,text=>{message=text;const el=document.querySelector('#dev-status');if(el)el.textContent=text;});
const esc=(s:unknown)=>String(s).replace(/[<>&"]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;'}[c]!));
const id=(prefix:string)=>{while(doc.preset.entities.some(e=>e.id===prefix+'-'+serial))serial++;return prefix+'-'+serial++;};
const update=()=>{view.selected=selected;view.replace(doc.preset);render();};
const change=(edit:(p:ScenarioPreset)=>void)=>{try{doc.change(edit);message='Draft updated · initial conditions only';update();}catch(e){notice(e);}};
function notice(e:unknown){message=e instanceof Error?e.message:String(e);render();}
const entity=()=>doc.preset.entities.find(e=>e.id===selected);
const options=(values:readonly string[],value:unknown)=>values.map(v=>`<option ${v===value?'selected':''} value="${esc(v)}">${esc(v)}</option>`).join('');
const refs=(type:string,value?:string)=>`<option value="">None</option>`+doc.preset.entities.filter(e=>e.type===type).map(e=>`<option value="${e.id}" ${e.id===value?'selected':''}>${esc(e.name)}</option>`).join('');
const numberField=(key:string,label:string,value:number,min=0,max=100000)=>`<label>${label}<input data-field="${key}" type="number" value="${value}" min="${min}" max="${max}" step="any"></label>`;
function inspector(e:ScenarioEntity):string{
 let html=`<label>Name<input data-field="name" value="${esc(e.name)}" maxlength="100"></label>`;
 if('side'in e)html+=`<label>Faction<select data-field="side">${options(['player','enemy'],e.side)}</select></label>`;
 if(e.type==='trench'){const t=view.session.state.trenches[doc.preset.entities.filter(v=>v.type==='trench').indexOf(e)],network=view.simulation.garrisons.network,component=t?network.component(t.id):undefined;html+=`<div class="readout">${polylineLength(e.points).toFixed(0)} m · ${e.points.length} control points<br>${component===undefined?'No completed traversable floor':network.capacity(component)+' connected capacity · production network'}</div><label>Excavation<select data-field="completed"><option value="true" ${e.completed?'selected':''}>Completed</option><option value="false" ${!e.completed?'selected':''}>Planned / impassable</option></select></label>${numberField('width','Width (m)',e.width,3,8)}${numberField('depth','Depth (m)',e.depth,.4,2.5)}<p>Drag numbered control points to reshape. Branch starts from a clicked point on this trench.</p><div class="row"><button id="branch">Branch</button><button id="extend">Extend</button></div>`;}
 if(e.type==='formation')html+=`<label>Equipment<select data-field="kind">${options(['rifle','engineer','machinegun','mortar','medical'],e.kind)}</select></label>${numberField('count','Personnel',e.count,1,32)}<label>Broad intention<select data-field="intent">${options(INTENTIONS,e.intent)}</select></label><label>Objective / staging<select data-field="targetId"><option value="">Commander chooses</option>${doc.preset.entities.filter(e=>e.type==='objective'||e.type==='staging').map(t=>`<option value="${t.id}" ${t.id===e.targetId?'selected':''}>${esc(t.name)}</option>`).join('')}</select></label><label>Initial trench assignment<select data-field="trenchId">${refs('trench',e.trenchId)}</select></label><details open><summary>Per-person finite supplies</summary>${numberField('ammo','Rifle rounds',e.ammo,0,600)}${numberField('food','Food',e.food,0,10)}${numberField('water','Water',e.water,0,10)}</details>`;
 if(e.type==='facility')html+=`<label>Parent trench<select data-field="trenchId">${refs('trench',e.trenchId)}</select></label><label>Installation<select data-field="installation">${options(['rest','meal','store','ammo','aid','crew-mg','mortar','field-gun'],e.weapon??e.kind)}</select></label>${numberField('facing','Facing (degrees)',e.facing,-360,360)}${e.weapon?`<label>Crew formation<select data-field="crewId">${refs('formation',e.crewId)}</select></label>`:''}`;
 if(e.type==='objective')html+=`<label>Initial control<select data-field="owner">${options(['neutral','player','enemy'],e.owner)}</select></label>${numberField('radius','Control radius (m)',e.radius,10,200)}`;
 if(e.type==='staging')html+=numberField('radius','Staging radius (m)',e.radius,10,200);
 if(e.type==='stock')html+='<p>Loose, recoverable stock. For a faction-controlled source, use a supply facility on that faction’s trench.</p>';
 if('stock'in e)html+=`<details open><summary>Finite initial stock</summary>${RESOURCES.map(r=>numberField('stock.'+r,r,e.stock[r])).join('')}</details>`;
 if(e.type==='trench')html+=`<label>Control point<select id="control-point">${e.points.map((_,i)=>`<option value="${i}">${i+1}</option>`).join('')}</select></label><button id="remove-point" ${e.points.length<=2?'disabled':''}>Remove control point</button>`;
 if(e.type==='facility')html+='<button id="snap-post">Snap to parent floor</button>';
 return html+`<div class="row"><button id="locate">Locate</button><button id="duplicate-item">Duplicate item</button><button id="delete-item" class="danger">Delete</button></div>`;
}
function render(){
 const openSections=new Set([...root.querySelectorAll('details[open]')].map(d=>d.querySelector('summary')?.textContent));
 const e=entity(),playing=view.playing;
 root.innerHTML=`<header><div class="brand">FRONTLINES <b>DEV</b><small>BATTLE SETUP AUTHORING</small></div><div class="document-name">${esc(doc.preset.name)} <span>${doc.dirty?'● UNSAVED':'SAVED'}</span></div><nav>${[['save','Save'],['duplicate','Duplicate'],['load','Load'],['play',playing?'Stop test':'Play Test'],['reset','Reset'],['publish','Use for title screen']].map(([action,label])=>`<button id="${action}" ${busy||playing&&!['play','reset'].includes(action)?'disabled':''} class="${action==='play'?'primary':''}">${label}</button>`).join('')}</nav></header>
 <aside class="tool-rail" ${playing?'hidden':''}><span class="caption">AUTHOR TOOLS</span>${[['select','↖ Select / move'],['trench','⌁ Draw trench'],['formation','× Formation'],['facility','⌂ Position / facility'],['stock','▣ Supply stock'],['objective','⚑ Objective'],['staging','R Staging area']].map(([key,label])=>`<button data-tool="${key}" aria-pressed="${tool===key}">${label}</button>`).join('')}<label>Placement faction<select id="placement-side">${options(['player','enemy'],side)}</select></label><div class="row"><button id="undo" ${!doc.canUndo?'disabled':''}>Undo</button><button id="redo" ${!doc.canRedo?'disabled':''}>Redo</button></div><button id="finish-draw" ${view.draft.length<2?'disabled':''}>Finish trench</button><button id="capture-camera">Set opening view</button><button id="opening-camera">Go to opening view</button><details><summary>Generated terrain</summary><label>Seed<input id="seed" type="number" min="1" max="2147483647" value="${doc.preset.seed}"></label><button id="generate">Regenerate terrain</button><p>Current production generator: ${doc.preset.worldSize/1000} × ${doc.preset.worldSize/1000} km. Roads, buildings and forests are read-only.</p></details><details><summary>Document / folder</summary><label>Preset name<input id="preset-name" value="${esc(doc.preset.name)}"></label><label>File identity<input id="preset-id" value="${doc.preset.id}" pattern="[a-z0-9_-]+"></label><label>Hour<input id="hour" type="number" min="0" max="23.99" value="${doc.preset.hour}"></label>${['player','enemy'].map(s=>`<label>${s} controller<select data-controller="${s}">${options(['ai','human'],doc.preset.controllers[s as 'player'|'enemy'])}</select></label>`).join('')}<p class="folder-path">${esc(store.label)}</p><button id="folder">Choose folder…</button>${projectFolder?`<button id="project-folder">Use project content folder</button><small>${esc(projectFolder)}</small>`:''}<button id="download">Download preset</button><label class="file-import">Import preset<input type="file" id="import" accept=".json,application/json"></label></details></aside>
 <aside class="inspector" ${playing?'hidden':''}><div class="caption">${e?'SELECTED '+e.type.toUpperCase():'SCENARIO CONTENT'}</div>${e?`<button id="deselect" class="back">← All content</button>${inspector(e)}`:`<p>Choose a tool, then click the terrain to place. Draw trenches by dragging or clicking a series of points.</p><div class="entity-list">${doc.preset.entities.map(e=>`<button data-select="${e.id}"><span>${e.type==='formation'?e.side==='enemy'?'E':'F':e.type.slice(0,1).toUpperCase()}</span>${esc(e.name)}</button>`).join('')||'<p>No authored items yet.</p>'}</div>`}</aside>
 ${playing?`<section class="test-controls"><b>ISOLATED PLAY TEST</b><span>Source preset and campaign saves are protected.</span><button id="test-pause">${view.speed?'Pause':'Resume'}</button><button id="test-speed">${view.speed===5?'1×':'5×'}</button><output id="test-stats"></output></section>`:''}
 <footer><span id="dev-status" role="status">${esc(message)}</span><small>WASD pan · wheel zoom · middle drag rotate · ${playing?'production simulation':'drag items / trench nodes · Esc cancel'} </small></footer>`;
 for(const d of root.querySelectorAll('details'))if(openSections.has(d.querySelector('summary')?.textContent))d.open=true;
 root.querySelectorAll<HTMLElement>('.tool-rail,.inspector').forEach(panel=>{panel.inert=busy;});
 const on=(selector:string,fn:(e:Event)=>void)=>root.querySelector(selector)?.addEventListener('click',fn);
 root.querySelectorAll<HTMLButtonElement>('[data-tool]').forEach(b=>b.onclick=()=>{tool=b.dataset.tool!;view.draft=[];message=tool==='select'?'Select a map item; drag to reposition.':tool==='trench'?'Drag a trench line, or click points then Finish trench.':'Click clear terrain to place '+tool+'.';render();});
 root.querySelectorAll<HTMLButtonElement>('[data-select]').forEach(b=>b.onclick=()=>{selected=b.dataset.select;view.selected=selected;render();});
 on('#deselect',()=>{selected=undefined;view.selected=undefined;render();});on('#locate',()=>{if(e)view.locate(e);});
 on('#remove-point',()=>{const index=Number(root.querySelector<HTMLSelectElement>('#control-point')!.value);if(e?.type==='trench'&&e.points.length>2)change(p=>{const t=p.entities.find(v=>v.id===e.id) as typeof e;t.points.splice(index,1);});});
 on('#snap-post',()=>{if(e?.type==='facility'){const hit=nearestTrench(e,e.trenchId);if(hit)change(p=>{const f=p.entities.find(v=>v.id===e.id) as typeof e;f.x=hit.point.x;f.z=hit.point.z;});}});
 on('#undo',()=>{doc.undo();update();});on('#redo',()=>{doc.redo();update();});on('#finish-draw',()=>finish());
 on('#branch',()=>{tool='branch';view.draft=[];message='Click a point on this trench, then draw a new branch.';render();});on('#extend',()=>{if(e?.type==='trench'){tool='extend';view.draft=[{...e.points.at(-1)!}];message='Draw onward from the end; Finish trench applies the extension.';render();}});
 on('#capture-camera',()=>change(p=>{p.camera=view.camera.capture();}));on('#opening-camera',()=>view.camera.restore(doc.preset.camera));
 on('#delete-item',()=>{if(!e)return;const dependent=doc.preset.entities.filter(v=>('trenchId'in v&&v.trenchId===e.id)||('crewId'in v&&v.crewId===e.id)||('targetId'in v&&v.targetId===e.id));if(dependent.length){notice('Cannot delete: referenced by '+dependent.map(v=>v.name).join(', ')+'. Clear those inspector assignments first.');return;}change(p=>{p.entities=p.entities.filter(v=>v.id!==e.id);});selected=undefined;render();});
 on('#duplicate-item',()=>{if(!e)return;const copy=structuredClone(e);copy.id=id(e.type);copy.name+=' copy';if(copy.type==='trench')copy.points=copy.points.map(p=>({x:p.x+15,z:p.z+15}));else if(copy.type!=='facility'){copy.x+=15;copy.z+=15;}else delete copy.crewId;selected=copy.id;change(p=>p.entities.push(copy));});
 root.querySelector<HTMLSelectElement>('#placement-side')?.addEventListener('change',event=>{side=(event.target as HTMLSelectElement).value as typeof side;});
 root.querySelectorAll<HTMLInputElement|HTMLSelectElement>('[data-field]').forEach(input=>input.onchange=()=>{if(!e)return;change(p=>{const target=p.entities.find(v=>v.id===e.id)!;const key=input.dataset.field!;if(key==='installation'&&target.type==='facility'){const v=input.value;if(['crew-mg','mortar','field-gun'].includes(v)){target.weapon=v as NonNullable<typeof target.weapon>;target.kind=v==='crew-mg'?'emplacement':'mortar';}else{target.kind=v as typeof target.kind;delete target.weapon;delete target.crewId;}}else if(key.startsWith('stock.')&&'stock'in target)target.stock[key.slice(6) as typeof RESOURCES[number]]=Number(input.value);else{const record=target as unknown as Record<string,unknown>;if(['targetId','trenchId','crewId'].includes(key)&&!input.value)delete record[key];else record[key]=key==='completed'?input.value==='true':input.type==='number'?Number(input.value):input.value;}});});
 for(const key of ['name','id','hour'] as const)root.querySelector<HTMLInputElement>('#'+(key==='hour'?'hour':'preset-'+key))?.addEventListener('change',event=>change(p=>{(p as unknown as Record<string,unknown>)[key]=key==='hour'?Number((event.target as HTMLInputElement).value):(event.target as HTMLInputElement).value;}));
 root.querySelectorAll<HTMLSelectElement>('[data-controller]').forEach(el=>el.onchange=()=>change(p=>{p.controllers[el.dataset.controller as 'player'|'enemy']=el.value as 'human'|'ai';}));
 on('#generate',()=>{const seed=Number(root.querySelector<HTMLInputElement>('#seed')!.value);if(confirm('Regenerate terrain beneath your authored items? Invalid placements will be reported; nothing is silently relocated.'))change(p=>{p.seed=seed;});});
 on('#folder',()=>run(async()=>{await store.choose();message='Folder selected: '+store.label;}));on('#project-folder',()=>run(async()=>{if(!await store.discover())throw new Error('Local project folder unavailable. Keep this document open or Download a copy.');store.chooseProject();message='Selected '+store.label+'. Save writes drafts; only Use for title screen changes the menu catalogue.';}));
 on('#save',()=>run(async()=>{const p=doc.preset,snapshot=JSON.stringify(p);await store.save(p);doc.markSaved(snapshot);message='Saved '+p.id+'.json to '+store.label;}));
 on('#duplicate',()=>{const next=prompt('New preset filename / identity',doc.preset.id+'-copy');if(next)run(async()=>{doc.duplicate(next);const snapshot=JSON.stringify(doc.preset);await store.save(doc.preset,true);doc.markSaved(snapshot);message='Created separate preset '+next;});});
 on('#load',()=>{if(doc.dirty&&!confirm('Discard unsaved authoring changes and load a preset?'))return;const name=prompt('Preset file identity (without .json)',doc.preset.id);if(name)run(async()=>{const p=await store.load(name);doc.load(p);selected=undefined;update();view.camera.restore(p.camera);message='Reopened '+name+'.json';});});
 on('#download',()=>{store.download(doc.preset);notice('Downloaded a runtime preset copy. Choose a folder to save updates or publish the title catalogue.');});
 root.querySelector<HTMLInputElement>('#import')?.addEventListener('change',event=>run(async()=>{const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;if(doc.dirty&&!confirm('Discard this unsaved document and import?'))return;doc.load(JSON.parse(await file.text()));selected=undefined;update();view.camera.restore(doc.preset.camera);message='Imported '+file.name;}));
 on('#publish',()=>run(async()=>{const p=doc.preset,state=instantiateScenario(p);if(state.soldiers.length<50||state.soldiers.length>100||!p.entities.some(e=>e.type==='objective')||p.controllers.player!=='ai'||p.controllers.enemy!=='ai'||state.operation!.initialPlayer<1||state.operation!.initialEnemy<1)throw new Error('Title battle needs 50–100 people, both AI controllers, both factions and an objective.');await store.publish(p);doc.markSaved(JSON.stringify(p));message='Published '+p.name+' for the title screen. Reload the normal game; rebuild to update offline/production packages.';}));
 on('#play',()=>{try{if(view.playing){view.replace(doc.preset);message='Stopped. Source initial conditions unchanged.';}else{instantiateScenario(doc.preset);view.replace(doc.preset,true);message='Production playtest running in an isolated session.';}view.camera.restore(doc.preset.camera);render();}catch(error){notice(error);}});
 on('#reset',()=>{try{if(view.playing){view.replace(doc.preset,true);view.camera.restore(doc.preset.camera);notice('Playtest reset from unchanged source preset.');}else if(confirm('Clear this document and start an empty authored sector?')){doc.load(blankScenario());selected=undefined;update();view.camera.restore(doc.preset.camera);}}catch(e){notice(e);}});
 on('#test-pause',()=>{view.speed=view.speed?0:1;render();});on('#test-speed',()=>{view.speed=view.speed===5?1:5;render();});
}
async function run(action:()=>Promise<void>){if(busy)return;busy=true;render();try{await action();}catch(e){message=(e instanceof Error?e.message:String(e))+' · document retained';}finally{busy=false;render();}}
function finish(){if(view.draft.length<2)return;const points=view.draft.map(p=>({...p}));if(polylineLength(points)<6){notice('Draw at least 6 metres.');return;}const extend=tool==='extend'?entity():undefined;view.draft=[];change(p=>{if(extend?.type==='trench'){const t=p.entities.find(e=>e.id===extend.id) as typeof extend;t.points.push(...points.slice(1));}else{const next=id('trench');p.entities.push({id:next,name:(side==='player'?'Friendly':'Opposing')+' trench '+serial,type:'trench',side,points,completed:true,width:4.2,depth:1.75});selected=next;}});tool='select';render();}
function nearestTrench(p:Vec2,only?:string){return doc.preset.entities.filter((e):e is Extract<ScenarioEntity,{type:'trench'}>=>e.type==='trench'&&(!only||e.id===only)).flatMap(e=>{const points=productionTrenchPath(e.points);return points.slice(1).map((b,i)=>{const a=points[i],hit=distanceToSegment(p,a,b);return {entity:e,distance:hit.distance,point:{x:a.x+(b.x-a.x)*hit.t,z:a.z+(b.z-a.z)*hit.t}};});}).sort((a,b)=>a.distance-b.distance)[0];}
function place(p:Vec2){const next=id(tool),base={id:next,name:tool[0].toUpperCase()+tool.slice(1)+' '+serial,x:Math.round(p.x*10)/10,z:Math.round(p.z*10)/10};let e:ScenarioEntity;
 if(tool==='formation')e={...base,type:'formation',side,kind:'rifle',count:8,intent:'attack',ammo:80,food:2,water:3};
 else if(tool==='facility'){const hit=nearestTrench(p);if(!hit||hit.distance>20){notice('Place a facility on a completed trench. Draw its connecting branch first.');return;}e={...base,...hit.point,type:'facility',kind:'rest',trenchId:hit.entity.id,facing:0,stock:inventory()};}
 else if(tool==='stock')e={...base,type:'stock',stock:inventory({ammo:240,food:24,water:36})};else if(tool==='objective')e={...base,type:'objective',owner:'neutral',radius:25};else e={...base,type:'staging',side,radius:30};selected=next;change(p=>p.entities.push(e));
}
let gesture:{start:{x:number;y:number};point:Vec2;node?:number;entityId?:string;draw:boolean;moved:boolean}|undefined;
canvas.addEventListener('pointerdown',event=>{if(busy||view.playing||event.button!==0)return;const p=view.camera.groundPoint(event.clientX,event.clientY);if(!p)return;canvas.setPointerCapture(event.pointerId);let node:number|undefined,entityId:string|undefined;
 if(['trench','branch','extend'].includes(tool)){if(tool==='branch'&&!view.draft.length){const hit=nearestTrench(p);if(!hit||hit.distance>12){notice('Start a branch on an existing trench.');return;}view.draft=[hit.point];}else if(!view.draft.length||distance(view.draft.at(-1)!,p)>2)view.draft.push(p);}
 else if(tool==='select'){
  const e=entity();if(e?.type==='trench'){node=e.points.findIndex(v=>{const s=view.camera.project(v);return Math.hypot(s.x-event.clientX,s.y-event.clientY)<12;});if(node<0)node=undefined;else entityId=e.id;}
  if(!entityId){const hit=doc.preset.entities.map(e=>({e,d:e.type==='trench'?Math.min(...e.points.slice(1).map((b,i)=>{const a=view.camera.project(e.points[i]),v=view.camera.project(b);return distanceToSegment({x:event.clientX,z:event.clientY},{x:a.x,z:a.y},{x:v.x,z:v.y}).distance;})):(()=>{const v=view.camera.project(e);return Math.hypot(v.x-event.clientX,v.y-event.clientY);})()})).filter(v=>v.d<22).sort((a,b)=>a.d-b.d)[0];selected=entityId=hit?.e.id;view.selected=selected;render();}
 }
 gesture={start:{x:event.clientX,y:event.clientY},point:p,node,entityId,draw:['trench','branch','extend'].includes(tool),moved:false};
});
canvas.addEventListener('pointermove',event=>{if(!gesture)return;const p=view.camera.groundPoint(event.clientX,event.clientY);if(!p)return;if(Math.hypot(event.clientX-gesture.start.x,event.clientY-gesture.start.y)>5)gesture.moved=true;if(gesture.draw&&gesture.moved&&distance(view.draft.at(-1)!,p)>8&&view.draft.length<128)view.draft.push(p);});
canvas.addEventListener('pointerup',event=>{if(!gesture)return;const g=gesture;gesture=undefined;if(busy)return;const p=view.camera.groundPoint(event.clientX,event.clientY);if(!p)return;
 if(g.draw){if(g.moved){if(distance(view.draft.at(-1)!,p)>1)view.draft.push(p);finish();}else render();return;}
 if(tool!=='select'){place(p);return;}
 if(g.entityId&&g.moved)change(preset=>{const e=preset.entities.find(e=>e.id===g.entityId)!;if(e.type==='trench'){if(g.node!==undefined)e.points[g.node]=p;else e.points=e.points.map(v=>({x:v.x+p.x-g.point.x,z:v.z+p.z-g.point.z}));}else if(e.type==='facility'){const hit=nearestTrench(p);if(!hit||hit.distance>20)throw new Error('Keep facilities on their connecting trench floor');e.x=hit.point.x;e.z=hit.point.z;e.trenchId=hit.entity.id;}else {e.x+=p.x-g.point.x;e.z+=p.z-g.point.z;}});
});
canvas.addEventListener('pointercancel',()=>{gesture=undefined;view.draft=[];});
window.addEventListener('keydown',event=>{if(busy||view.playing||(event.target as HTMLElement).closest('input,select,textarea'))return;if(event.key==='Escape'){gesture=undefined;view.draft=[];tool='select';render();}if(event.key==='Enter'&&view.draft.length>1)finish();if(event.ctrlKey&&event.key==='z'){event.preventDefault();event.shiftKey?doc.redo():doc.undo();update();}});
window.addEventListener('beforeunload',event=>{if(doc.dirty){event.preventDefault();event.returnValue='';}});
setInterval(()=>{const el=document.querySelector('#test-stats'),s=view.session.state;if(el)el.textContent=`${s.elapsed.toFixed(0)} s · ${s.operation?.shots??0} shots · ${s.soldiers.filter(s=>s.needs?.life==='dead').length} dead · ${s.operation?.status??'no operation'}`;},500);
update();view.camera.restore(doc.preset.camera);void store.discover().then(path=>{projectFolder=path;render();});
(window as unknown as {__FRONTLINES_DEV__:unknown}).__FRONTLINES_DEV__={inspect:()=>({source:structuredClone(doc.preset),dirty:doc.dirty,playing:view.playing,ownership:{...WorldSession.ownership},gpu:{...view.renderer.info.memory},runtime:structuredClone(view.session.state)})};
